Repository DrBackmischung/Kino-Backend, pull requests merged in 2021-12, with the labels that each got.

#23 KINO-147
  .github/badges/jacoco.svg
  Postman/Cinema API DELETE.postman_collection.json
  Postman/Cinema API GET.postman_collection.json
  Postman/Cinema API PUT.postman_collection.json
  src/main/java/de/wi2020sebgroup1/cinema/controller/MovieController.java
  src/main/java/de/wi2020sebgroup1/cinema/controller/PriceController.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/Movie.java
  src/main/java/de/wi2020sebgroup1/cinema/repositories/ShowRepository.java
  src/test/java/de/wi2020sebgroup1/cinema/entities/MovieTest.java
  src/test/java/de/wi2020sebgroup1/cinema/entities/ShowTest.java
Labels: enhancement

#11 Kino-68
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  src/main/java/de/wi2020sebgroup1/cinema/controller/CinemaController.java
  src/main/java/de/wi2020sebgroup1/cinema/controller/CinemaRoomController.java
  src/main/java/de/wi2020sebgroup1/cinema/controller/CinemaRoomSeatingPlanController.java
  src/main/java/de/wi2020sebgroup1/cinema/controller/CityController.java
  src/main/java/de/wi2020sebgroup1/cinema/controller/MovieController.java
  src/main/java/de/wi2020sebgroup1/cinema/controller/PriceController.java
  src/main/java/de/wi2020sebgroup1/cinema/controller/ShowController.java
  src/main/java/de/wi2020sebgroup1/cinema/controller/TicketController.java
  src/main/java/de/wi2020sebgroup1/cinema/controller/UserController.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/Cinema.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/CinemaRoom.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/CinemaRoomSeatingPlan.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/City.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/Movie.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/Seat.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/Show.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/Ticket.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/User.java
  src/main/java/de/wi2020sebgroup1/cinema/repositories/CityRepository.java
  src/main/resources/application.properties
  src/main/resources/test.properties
  src/test/java/de/wi2020sebgroup1/cinema/controller/CinemaControllerTest.java
  src/test/java/de/wi2020sebgroup1/cinema/controller/CinemaRoomControllerTest.java
  src/test/java/de/wi2020sebgroup1/cinema/controller/CinemaRoomSeatingPlanControllerTest.java
  src/test/java/de/wi2020sebgroup1/cinema/controller/CityControllerTest.java
  src/test/java/de/wi2020sebgroup1/cinema/controller/MovieControllerTest.java
  src/test/java/de/wi2020sebgroup1/cinema/controller/PriceControllerTest.java
  src/test/java/de/wi2020sebgroup1/cinema/controller/ShowControllerTest.java
  src/test/java/de/wi2020sebgroup1/cinema/controller/TicketControllerTest.java
  src/test/java/de/wi2020sebgroup1/cinema/controller/UserControllerTest.java
  src/test/java/de/wi2020sebgroup1/cinema/entities/CityTest.java
Labels: In Progress!

#29 Kino-191
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  src/main/java/de/wi2020sebgroup1/cinema/controller/ShowController.java
  src/main/java/de/wi2020sebgroup1/cinema/controller/TicketController.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/Cinema.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/CinemaRoom.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/CinemaRoomSeatingPlan.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/City.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/Movie.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/Price.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/Role.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/Seat.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/Show.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/Ticket.java
  src/main/java/de/wi2020sebgroup1/cinema/entities/User.java
  src/test/java/de/wi2020sebgroup1/cinema/controller/CinemaRoomSeatingPlanControllerTest.java
  src/test/java/de/wi2020sebgroup1/cinema/controller/ShowControllerTest.java
  src/test/java/de/wi2020sebgroup1/cinema/controller/TicketControllerTest.java
  src/test/java/de/wi2020sebgroup1/cinema/entities/CinemaRoomSeatingPlanTest.java
  src/test/java/de/wi2020sebgroup1/cinema/entities/CinemaRoomTest.java
  src/test/java/de/wi2020sebgroup1/cinema/entities/CinemaTest.java
  src/test/java/de/wi2020sebgroup1/cinema/entities/CityTest.java
  src/test/java/de/wi2020sebgroup1/cinema/entities/MovieTest.java
  src/test/java/de/wi2020sebgroup1/cinema/entities/PriceTest.java
  src/test/java/de/wi2020sebgroup1/cinema/entities/RoleTest.java
  src/test/java/de/wi2020sebgroup1/cinema/entities/SeatTest.java
  src/test/java/de/wi2020sebgroup1/cinema/entities/ShowTest.java
  src/test/java/de/wi2020sebgroup1/cinema/entities/TicketTest.java
  src/test/java/de/wi2020sebgroup1/cinema/entities/UserTest.java
Labels: Do not merge!

#31 KINO-201
  src/main/java/de/wi2020sebgroup1/cinema/entities/Movie.java
  src/test/java/de/wi2020sebgroup1/cinema/entities/MovieTest.java
Labels: Do not merge!
